languageCode = 'en-uk'
title = 'G10 OER'
# theme = 'hugo-theme-relearn'
baseURL = 'gektec.github.io/G10/'

[module]
    # uncomment line below for temporary local development of module
    # or when using a 'theme' as a git submodule
    # replacements = "github.com/colinwilson/lotusdocs -> lotusdocs"
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false

[params]
    alwaysopen = true
    collapsibleMenu=true
    ordersectionsby = 'title'
    [[params.themeVariant]]
        auto = []
        identifier = 'relearn-auto'
        name = 'Auto switch theme'

    [[params.themeVariant]]
        identifier = 'relearn-light'
        name = 'Light'

    [[params.themeVariant]]
        identifier = 'relearn-dark'
        name = 'Dark'

[menu]
  [[menu.shortcuts]]
    pre = '<i class="fa-fw fab fa-github"></i> '
    name = 'GitHub Repo'
    url = 'https://github.com/gektec/G10'
    weight = 1

  [[menu.shortcuts]]
    name = 'Merlot'
    url = 'https://merlot.org/merlot/viewMaterial.htm?id=773474103'
    weight = 2

  [[menu.shortcuts]]
    name = '2023 Group8 OER'
    url = 'https://www.merlot.org/merlot/viewSite.htm?id=9166460'
    weight = 3
  
