languageCode = 'en-uk'
title = 'G10 OER'
theme = 'hugo-theme-relearn'
[params]
    alwaysopen = true
    collapsibleMenu=true
    ordersectionsby = 'title'
    [[params.themeVariant]]
        auto = []
        identifier = 'relearn-auto'
        name = 'Auto switch theme'

    [[params.themeVariant]]
        identifier = 'relearn-light'
        name = 'Light'

    [[params.themeVariant]]
        identifier = 'relearn-dark'
        name = 'Dark'

    